// This code was generated by TFT Screen Layout Helper by Luiz F. R. Pimentel
// Estimated Flash Usage for image data: 0 Bytes
// Mode: Internal Memory

#pragma once

#include <TFT_eSPI.h>

// --- Drawing Functions (Individual Elements) ---
// Name: text_1
void draw_text_1(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0x0408);
    tft.drawString("Memoria Interna OK", 4, 103);
}

// Name: text_2
void draw_text_2(TFT_eSPI &tft)
{
    tft.setTextSize(3);
    tft.setTextColor(0x801F);
    tft.drawString("Crie textos!", 9, -1);
}

// Name: text_3
void draw_text_3(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0x001F);
    tft.drawString("C", 58, 26);
}

// Name: text_4
void draw_text_4(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0x841F);
    tft.drawString("O", 73, 28);
}

// Name: text_5
void draw_text_5(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0xFFFF);
    tft.drawString("L", 90, 27);
}

// Name: text_6
void draw_text_6(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0x07F0);
    tft.drawString("O", 106, 29);
}

// Name: text_7
void draw_text_7(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0x801F);
    tft.drawString("R", 122, 26);
}

// Name: text_8
void draw_text_8(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0xFC08);
    tft.drawString("I", 134, 28);
}

// Name: text_9
void draw_text_9(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0xB828);
    tft.drawString("D", 147, 29);
}

// Name: text_10
void draw_text_10(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0x4410);
    tft.drawString("O", 161, 30);
}

// Name: text_11
void draw_text_11(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0xF810);
    tft.drawString("S", 174, 28);
}

// Name: text_12
void draw_text_12(TFT_eSPI &tft)
{
    tft.setTextSize(1);
    tft.setTextColor(0x07F0);
    tft.drawString("Com qualquer tamanho", 56, 51);
}

// Name: text_13
void draw_text_13(TFT_eSPI &tft)
{
    tft.setTextSize(2);
    tft.setTextColor(0xC474);
    tft.drawString("Do it Yourself", 29, 75);
}

// --- Main Drawing Function (All Elements) ---
void drawLayout(TFT_eSPI &tft)
{
    draw_text_1(tft);
    draw_text_2(tft);
    draw_text_3(tft);
    draw_text_4(tft);
    draw_text_5(tft);
    draw_text_6(tft);
    draw_text_7(tft);
    draw_text_8(tft);
    draw_text_9(tft);
    draw_text_10(tft);
    draw_text_11(tft);
    draw_text_12(tft);
    draw_text_13(tft);
}
